<p>I asked the question the pymc developers on GitHub and there I got an answer from fonnesbeck (<a href="https://github.com/pymc-devs/pymc/issues/47#issuecomment-129301002" rel="nofollow">https://github.com/pymc-devs/pymc/issues/47#issuecomment-129301002</a>):</p>

<blockquote>
  <p>This is because you filled the missing values with 999999, which is outside the support of the variable. You need to give it a valid value, but not one that occurs in the non-missing data."</p>
</blockquote>

<p>To make sure that the missing value is not in the non-missing data the following was suggested:</p>

<blockquote>
  <p>You can give it a non-integer value in order to avoid the problem that you cite. For example, if you fill with, say, 1.5 that should work.</p>
  
  <p>(...) PyMC calculates the log-probability at the first iteration, and therefore the values inserted for the missing values at the first iteration have to be valid. If you give discrete values a floating point value, it should end up getting truncated when converted to integers, so that will work."</p>
</blockquote>
