<p>It seems that there is a bug in the creation of gimp.GroupLayer - and it behaves as a normal layer, even though the object type, in Python, is shown as a group-layer.</p>

<p>It is possible to create a working group layer through the PDB, though, using <code>pdb.gimp_layer_group_new(img)</code> - this time, tehre is another bug, the object appears in Python as being a nromal Layer object - but after inserting it in the image with
<code>pdb.gimp_image_insert_layer(image, layer, &lt;parent (use None for top level)&gt;, &lt;position&gt;)</code> it works properly (and retrieving the object through the image "layer" attribute will give you
a proper GroupLayer object).</p>

<p>Sorry for that - most of it is my fault - I will see if I can get the behavior fixed for the next GIMP 2.8 - GIMP 2.8 almost shipped with no support for layer groups from Python at all.</p>

<p><strong>update</strong>: As of GIMP 2.8.12, calling gimp.GroupLayer(image, ...) creates a proper layer group. </p>
