<p>I see you are using get_nowait() which according to the documentation, "return[s] an item if one is immediately available, else raise the Empty exception"</p>

<p>Now, you happen to break out of the loop when an Empty exception is thrown. Thus, if there is no result immediately available in the queue, your function returns an empty items list.</p>

<p>Is there a reason why you are not using the get() method instead? It may be the case that the get_nowait() fails because the queue is servicing a put() request at that same moment. </p>
