<p>Wrap the inner contents of the loop in a <code>try ... catch</code> block.</p>

<p>e.g.</p>

<pre><code>foreach (var foo in iterableThing) {
    try {
        DoStuff(foo);
    }
    catch (AppropriateException) {
        // Handle the exception (or ignore it)...
    }
    catch (SomeOtherException) {
        // Handle the exception (or ignore it)...
    }
}
</code></pre>
