<p>In Tk the root window is named '.' (dot) and its children are named as a dot delimited path of parent names. Tkinter generates the names for you using numbers. The other thing to note is that in Tk the name of a window is also a command that provides operations on that window. So the error you have here is telling you that one of your windows no longer exists as the command that manages it is gone. I suggest that your <code>bub_id</code> list is being modified while you iterate over it leaving you with the potential to obtain a window name that has been destroyed elsewhere. You can avoid the error using <code>c.winfo_exists</code> which lets you know if the window is actually existing and works even if the window has been destroyed. But really you should try to avoid making calls on destroyed windows.</p>

<p>Here's a small example that produces the same error:</p>

<pre><code>&gt;&gt;&gt; import tkinter as tk
&gt;&gt;&gt; main = tk.Tk()
&gt;&gt;&gt; b = tk.Label(main, text="hello")
&gt;&gt;&gt; b.destroy()
&gt;&gt;&gt; b.configure()
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1322, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1310, in _configure
    return self._getconfigure(_flatten((self._w, cmd)))
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1294, in _getconfigure
    for x in self.tk.splitlist(self.tk.call(*args)):
_tkinter.TclError: invalid command name ".140685140686048"
&gt;&gt;&gt; b.winfo_exists()
0
&gt;&gt;&gt; 
</code></pre>
