<p>The <code>for</code> loop is indented incorrectly resulting in it being outside that method's scope but inside the class' scope. This in turn means that <code>self</code> is not defined.</p>

<p>Python does interpret that loop code in the scope of the class, but without an instance of the object. Sample malformed code:</p>

<pre><code>class Simple(object):
    def __init__(self, a):
        self.a = a

    print("Here we go!")
    for i in xrange(self.a):
        print(i)
</code></pre>

<p>Traceback</p>

<pre><code>$ python simple.py
Here we go!
Traceback (most recent call last):
  File "simple.py", line 4, in &lt;module&gt;
    class Simple(object):
  File "simple.py", line 9, in Simple
    for i in xrange(self.a):
NameError: name 'self' is not defined
</code></pre>
