<p>You can implement the given example with <a href="https://docs.python.org/3.5/library/functions.html#sum" rel="nofollow"><code>sum</code></a> and <a href="https://docs.python.org/3.5/reference/expressions.html#generator-expressions" rel="nofollow">generator expression</a> that returns <code>dict</code> values based on keys:</p>

<pre><code>&gt;&gt;&gt; d = {'a': 11, 'b': 4, 'c': 7, 'd': 12, 'e': 5}
&gt;&gt;&gt; keys_list_to_add = ['a', 'b', 'e']
&gt;&gt;&gt; sum(d[k] for k in keys_list_to_add)
20
</code></pre>

<p>It raises <code>KeyError</code> in case that given key doesn't exists in the <code>dict</code>:</p>

<pre><code>&gt;&gt;&gt; keys_list_to_add = ['a', 'b', 'f']
&gt;&gt;&gt; sum(d[k] for k in keys_list_to_add)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 1, in &lt;genexpr&gt;
KeyError: 'f'
</code></pre>

<p>If you want to handle the error in one way or another you could use <code>try/except</code>:</p>

<pre><code>&gt;&gt;&gt; try:
...     sum(d[k] for k in keys_list_to_add)
... except KeyError:
...     print 'Missing key'
...
Missing key
</code></pre>

<p>Or you could interpret missing key as <code>0</code>:</p>

<pre><code>&gt;&gt;&gt; sum(d.get(k, 0) for k in keys_list_to_add)
15
</code></pre>

<p>Note that you shouldn't use build-in method names like <code>dict</code> for variables since that hides the method:</p>

<pre><code>&gt;&gt;&gt; dict(a=1)
{'a': 1}
&gt;&gt;&gt; dict = {1:2}
&gt;&gt;&gt; dict(a=1)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
TypeError: 'dict' object is not callable
</code></pre>
