<p>It sounds like you're not running the contract rewriter on the assembly when running the unit test manually, so that the Requires contracts never result in exceptions.  It instead sounds like you have some manual checking code inside your method that throws ArgumentOutOfRangeException, which is the correct behavior (at runtime, with no contract rewriting), but doesn't match your expected exception for the test.  Make sure that you have the Code Contracts rewriter installed and make sure the Project settings include rewriting with exceptions.</p>

<p>Alternately, use the Requires overload that specifies an Exception type so that it matches the internal check.  In this case, you might even remove the other explicit exception, as long as you know you plan to use rewriting.</p>

<pre><code>Contract.Requires&lt;ArgumentOutOfRangeException&gt;( ( qtrs * 3 ) &gt;= -120000 &amp;&amp; ( qtrs * 3 ) &lt;= 120000 , "qtrs");
</code></pre>
